// Stub for Convex server - will be regenerated by convex dev
export const internalMutation = (fn: any) => fn;
export const mutation = (fn: any) => fn;
export const query = (fn: any) => fn;
export const action = (fn: any) => fn;
export const internalAction = (fn: any) => fn;
export const httpAction = (fn: any) => fn;
